var localize = {
    "en-US": {
        "library": "Library",
        "gameCenter": "Game center",
        "helpCenter": "Help",
        "playAndWin": "Play and win",
        "search": "Search",
        "allInstalled": "All installed",
        "bluestacksApps": "BlueStacks apps",
        "noInternet": "You are not connected to the Internet. Please restore your Internet connection.",
        "blog": "Blog",
        "systemApps": "System apps",
        "installApk": "Install APK",
        "deleteApps": "Delete apps",
        "delete": "Delete",
        "cancel": "Cancel",
        "areYouSure": "Are you sure you want to delete the selected app. You will loose all the unsaved game data.",
        "installingApp": "Installing app",
        "newApp": "New app",
        "installFailed": "Install failed",
        "retry": "Retry",
        "reload": "Reload"
    },
    "tr-TR": {
        "library": "Kütüphane",
        "gameCenter": "Oyun Merkezi",
        "helpCenter": "Yardım",
        "playAndWin": "Oyna ve kazan!",
        "search": "Araştır",
        "allInstalled": "Hepsi yüklendi",
        "bluestacksApps": "BlueStacks uygulamaları",
        "noInternet": "İnternete bağlı değilsiniz. Lütfen internet bağlantınızın çalıştığından emin olun.",
        "blog": "Blog",
        "systemApps": "Sistem uygulamaları",
        "installApk": "APK Yükle",
        "deleteApps": "Uygulamaları Sil",
        "delete": "Sil",
        "cancel": "İptal",
        "areYouSure": "Seçilli uygulamayı silmek istediğinizden emin misiniz? Tüm kaydedilmemiş oyun bilgilerini kaybedeceksiniz.",
        "installingApp": "Uygulama yükleniyor",
        "newApp": "Yeni uygulama",
        "installFailed": "Yükleme Başarısız",
        "retry": "Yeniden dene",
        "reload": "Yeniden Yükle"
    },
    "th-TH": {
        "library": "Library",
        "gameCenter": "Game center",
        "helpCenter": "ช่วยเหลือ",
        "playAndWin": "เล่นแล้วลุ้น",
        "search": "ค้นหา",
        "allInstalled": "All installed",
        "bluestacksApps": "Bluestacks apps",
        "noInternet": "คุณไม่ได้เชื่อมต่ออินเตอร์เน็ต กรุณาทำการเชื่อมต่อก่อน",
        "blog": "Blog",
        "systemApps": "System apps",
        "installApk": "ติดตั้ง APK",
        "deleteApps": "ลบแอป",
        "delete": "ลบ",
        "cancel": "ยกเลิก",
        "areYouSure": "คุณแน่ใจหรือไม่ว่าต้องการถอนการติดตั้งแอพที่เลือก ข้อมูลทั้งหมดจะถูกลบ",
        "installingApp": "กำลังติดตั้ง App",
        "newApp": "New app",
        "installFailed": "ติดตั้งล้มเหลว",
        "retry": "ลองใหม่อีกครั้ง",
        "reload": "รีเฟรช"
    },
    "es-ES": {
        "library": "Biblioteca",
        "gameCenter": "Game center",
        "helpCenter": "Ayuda",
        "playAndWin": "Juega y gana",
        "search": "Búsqueda",
        "allInstalled": "Todo instalado",
        "bluestacksApps": "Aplicaciones BlueStacks",
        "noInternet": "No estás conectado a Internet. Por favor restablezca su conexión a Internet.",
        "blog": "Blog",
        "systemApps": "Aplicaciones del sistema",
        "installApk": "Instalar APK",
        "deleteApps": "Eliminar aplicaciones",
        "delete": "Eliminar",
        "cancel": "Cancelar",
        "areYouSure": "¿Está seguro de que desea eliminar la aplicación seleccionada? Perderás todos los datos del juego no guardados.",
        "installingApp": "Instalando aplicación",
        "newApp": "Nueva aplicación",
        "installFailed": "Instalación fallida",
        "retry": "Rever",
        "reload": "Recargar"
    },
    "ru-RU": {
        "library": "Библиотека",
        "gameCenter": "Игровой центр",
        "helpCenter": "Помощь",
        "playAndWin": "Играйте и выигрывайте",
        "search": "Поиск",
        "allInstalled": "Установлено",
        "bluestacksApps": "Приложения BlueStacks",
        "noInternet": "Вы не подключены к Интернету. Пожалуйста, восстановите ваше Интернет-соединение.",
        "blog": "Блог",
        "systemApps": "Системные приложения",
        "installApk": "Установить APK",
        "deleteApps": "Удалить приложения",
        "cancel": "Отменить",
        "areYouSure": "Вы уверены, что желаете удалить выбранное приложение? Вы можете потерять несохраненные игровые данные.",
        "installingApp": "Устанавливаем приложение",
        "newApp": "Новое приложение",
        "installFailed": "Установка не удалась",
        "reload": "Обновить"
    },
    "pt-BR": {
        "library": "Biblioteca",
        "gameCenter": "Central de Jogos ",
        "helpCenter": "Ajuda",
        "playAndWin": "Jogue e ganhe!",
        "search": "Pesquisar",
        "allInstalled": "Todos instalados ",
        "bluestacksApps": "Aplicativos BlueStacks ",
        "noInternet": "Você não está conectado à Internet. Por favor, restaure sua conexão com a Internet.",
        "blog": "Blog",
        "systemApps": "Aplicativo do Sistema",
        "installApk": "Instalar APK",
        "deleteApps": "Excluir aplicativos",
        "delete": "Deletar",
        "cancel": "Cancelar",
        "areYouSure": "Tem certeza de que deseja excluir o aplicativo selecionado. Você perderá todos os dados do jogo não salvos.",
        "installingApp": "Instalando aplicativo ",
        "newApp": "Novo aplicativo ",
        "installFailed": "Falha na instalação",
        "retry": "Tentar novamente",
        "reload": "Recarregar"
    },
    "pl-PL": {
        "library": "Biblioteka",
        "gameCenter": "Centrum gier",
        "helpCenter": "Pomoc",
        "playAndWin": "Graj i wygrywaj!",
        "search": "Szukaj",
        "allInstalled": "Wszystkie zainstalowane",
        "bluestacksApps": "Aplikacje BlueStacks",
        "noInternet": "Nie jesteś połączony z internetem. Proszę podłączyć się do internetu.",
        "blog": "Blog",
        "systemApps": "Aplikacje systemowe",
        "installApk": "Zainstaluj APK",
        "deleteApps": "Usuń aplikacje",
        "delete": "Usuń",
        "cancel": "Anuluj",
        "areYouSure": "Czy na pewno chcesz usunąć wybraną aplikację? Utracisz wszystkie zapisane dane gry.",
        "installingApp": "Instalowanie aplikacji",
        "newApp": "Nowa aplikacja",
        "installFailed": "Instalacja nieudana",
        "retry": "Spróbować ponownie",
        "reload": "Przeładuj"
    },
    "ko-KR": {
        "library": "서재",
        "gameCenter": "게임 센터",
        "helpCenter": "도움말",
        "playAndWin": "Play & win",
        "search": "검색",
        "allInstalled": "모두 설치",
        "bluestacksApps": "블루스택 앱",
        "noInternet": "인터넷에 연결되어 있지 않습니다. 인터넷 연결을 복원하십시오.",
        "blog": "블로그",
        "systemApps": "시스템 앱",
        "installApk": "APK 설치",
        "deleteApps": "앱 삭제",
        "delete": "삭제",
        "cancel": "취소",
        "areYouSure": "선택한 앱을 삭제 하시겠습니까? 저장된 게임 데이터가 모두 손실됩니다.",
        "installingApp": "설치중인 앱",
        "newApp": "새로운 앱",
        "installFailed": "설치 실패",
        "retry": "다시 시도",
        "reload": "다시로드하기"
    },
    "ja-JP": {
        "library": "ライブラリー",
        "gameCenter": "ゲームセンター",
        "helpCenter": "お問い合わせ",
        "playAndWin": "Play and Win!",
        "search": "検索",
        "allInstalled": "すべてインストール済み",
        "bluestacksApps": "BlueStacksアプリ",
        "noInternet": "インターネットに接続されていません。 インターネット接続を復元してください。",
        "blog": "ブログ",
        "systemApps": "システムアプリ",
        "installApk": "インストールAPK",
        "deleteApps": "アプリを削除",
        "delete": "削除",
        "cancel": "キャンセル",
        "areYouSure": "選択されたアプリを削除してよろしいですか？保存されていないゲームデータがすべて失われます。",
        "installingApp": "アプリのインストール中",
        "newApp": "新しいアプリ",
        "installFailed": "インストールできませんでした。",
        "retry": "リトライ",
        "reload": "リロード"
    },
    "it-IT": {
        "library": "Biblioteca",
        "gameCenter": "Game center",
        "helpCenter": "Aiuto",
        "playAndWin": "Gioca e vinci!",
        "search": "Cerca",
        "allInstalled": "Tutto installato",
        "bluestacksApps": "App BlueStacks",
        "noInternet": "Non sei connesso a Internet. Si prega di ripristinare la connessione a Internet.",
        "blog": "blog",
        "systemApps": "App di sistema",
        "installApk": "Installa APK",
        "deleteApps": "Cancella App",
        "delete": "Cancella",
        "cancel": "Cancella",
        "areYouSure": "Sei sicuro di voler eliminare l'app selezionata. Perderai tutti i dati di gioco non salvati.",
        "installingApp": "Installazione dell'app",
        "newApp": "Nuova app",
        "installFailed": "Installazione non riuscita",
        "retry": "Riprova",
        "reload": "Ricarica"
    },
    "de-DE": {
        "library": "Bibliothek",
        "gameCenter": "Game Center",
        "helpCenter": "Hilfe",
        "playAndWin": "Spiele und gewinne",
        "search": "Suche",
        "allInstalled": "Alle installierten",
        "bluestacksApps": "BlueStacks-Apps",
        "noInternet": "Du bist nicht mit dem Internet verbunden. Bitte stell deine Internetverbindung wieder her.",
        "blog": "Blog",
        "systemApps": "System-Apps",
        "installApk": "APK installieren",
        "deleteApps": "Apps löschen",
        "delete": "Löschen",
        "cancel": "Abbrechen",
        "areYouSure": "Möchtest du die ausgewählte App wirklich löschen? Du verlierst alle nicht gespeicherten Spieldaten.",
        "installingApp": "App wird installiert",
        "newApp": "Neue App",
        "installFailed": "Installation fehlgeschlagen",
        "retry": "Wiederholen",
        "reload": "Aktualisieren"
    },
    "fr-FR": {
        "library": "Bibliothèque",
        "gameCenter": "Centre de jeu",
        "helpCenter": "Aide",
        "playAndWin": "Jouer et gagner",
        "search": "Chercher",
        "allInstalled": "Tous installés",
        "bluestacksApps": "Applications Bluestacks",
        "noInternet": "Vous n'êtes pas connecté à Internet. Veuillez rétablir votre connexion Internet.",
        "blog": "Blog",
        "systemApps": "Applications système",
        "installApk": "Installer l'APK",
        "deleteApps": "Supprimer les applications",
        "delete": "Effacer",
        "cancel": "Annuler",
        "areYouSure": "Voulez-vous vraiment supprimer l'application sélectionnée? Vous perdrez toutes les données de jeu non enregistrées.",
        "installingApp": "Installation de l'application",
        "newApp": "Nouvelle application",
        "installFailed": "Échec de l'installation",
        "retry": "Réessayer",
        "reload": "Recharger"
    },
    "zh-TW": {
        "library": "首頁",
        "gameCenter": "遊戲中心",
        "helpCenter": "幫助",
        "playAndWin": "遊玩並獲得勝利",
        "search": "搜索",
        "allInstalled": "已安裝的應用程式",
        "bluestacksApps": "Bluestacks中的應用",
        "noInternet": "您沒有連接網絡。 請恢復您的網絡連接。",
        "blog": "部落格",
        "systemApps": "系統應用程式",
        "installApk": "安裝APK",
        "deleteApps": "刪除應用程式",
        "delete": "刪除",
        "cancel": "取消",
        "areYouSure": "您確定要刪除所選的應用程式嗎? 您將失去此遊戲中已保存的所有數據。",
        "installingApp": "正在安裝應用",
        "newApp": "新遊戲",
        "installFailed": "安裝失敗",
        "retry": "重試",
        "reload": "重載"
    },
    "ar-EG": {
        "library": "مكتبة",
        "gameCenter": "مركز الالعاب",
        "helpCenter": "مساعدة",
        "playAndWin": "إلعب وفز!",
        "search": "بحث",
        "allInstalled": "كل تثبيت",
        "bluestacksApps": "تطبيقات بلوستاكس",
        "noInternet": "أنت غير متصل بالإنترنت. يرجى استعادة اتصال الإنترنت الخاص بك.",
        "blog": "مدونة",
        "systemApps": "تطبيقات النظام",
        "installApk": "تثبيت APK",
        "deleteApps": "حذف التطبيقات",
        "delete": "حذف",
        "cancel": "إلغاء",
        "areYouSure": "هل أنت متأكد أنك تريد حذف التطبيق المحدد. ستفقد جميع بيانات اللعبة غير المحفوظة.",
        "installingApp": "تثبيت التطبيق",
        "newApp": "تطبيق جديد",
        "installFailed": "فشل تثبيت",
        "retry": "إعادة المحاولة",
        "reload": "إعادة تحميل"
    },
    "vi-VN": {
        "library": "Thư viện",
        "gameCenter": "Trung tâm trò chơi",
        "helpCenter": "Giúp đỡ",
        "playAndWin": "Chơi và thắng!",
        "search": "Tìm kiếm",
        "allInstalled": "Tất cả đã được cài đặt",
        "bluestacksApps": "Ứng dụng BlueStacks",
        "noInternet": "Bạn không kết nối với Internet. Vui lòng khôi phục kết nối internet của bạn.",
        "blog": "Blog",
        "systemApps": "Ứng dụng hệ thống",
        "installApk": "Cài đặt apk",
        "deleteApps": "Xóa ứng dụng",
        "delete": "Xóa",
        "cancel": "Hủy",
        "areYouSure": "Bạn có chắc bạn muốn xóa các ứng dụng đã chọn. Bạn sẽ mất tất cả dữ liệu chưa được lưu.",
        "installingApp": "Đang cài đặt ứng dụng",
        "newApp": "Ứng dụng mới",
        "installFailed": "Cài đặt thất bại",
        "retry": "Thử lại",
        "reload": "Tải lại"
    },
    "zh-TW": {
        "library": "首頁",
        "gameCenter": "遊戲中心",
        "helpCenter": "幫助",
        "playAndWin": "遊玩並獲得勝利",
        "search": "搜索",
        "allInstalled": "已安裝的應用程式",
        "bluestacksApps": "Bluestacks中的應用",
        "noInternet": "您沒有連接網絡。 請恢復您的網絡連接。",
        "blog": "部落格",
        "systemApps": "系統應用程式",
        "installApk": "安裝APK",
        "deleteApps": "刪除應用程式",
        "delete": "刪除",
        "cancel": "取消",
        "areYouSure": "您確定要刪除所選的應用程式嗎? 您將失去此遊戲中已保存的所有數據。",
        "installingApp": "正在安裝應用",
        "newApp": "新遊戲",
        "installFailed": "安裝失敗",
        "retry": "重試",
        "reload": "重載"
    }
}